# Generated by Django 5.0.6 on 2024-06-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('svgKey', models.CharField(max_length=20)),
                ('category_ru', models.CharField(blank=True, max_length=20, null=True)),
                ('category_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(blank=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bill_text', models.JSONField(blank=True, null=True)),
                ('ai_model', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsListDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_permissions', models.JSONField(auto_created={'admin': False, 'read': False, 'write': False})),
                ('permissions_owner', models.JSONField(auto_created={'admin': True, 'read': True, 'write': True})),
                ('name', models.CharField(max_length=50, unique=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_lists', to=settings.AUTH_USER_MODEL)),
                ('shared_with_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
