# Generated by Django 5.0.6 on 2024-06-27 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0002_customproductmodel_customuser_user_theme_billmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslistdatamodel',
            name='permissions_owner',
            field=models.JSONField(default={'admin': True, 'read': True, 'write': True}),
        ),
        migrations.AlterField(
            model_name='productslistdatamodel',
            name='shared_with_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productslistdatamodel',
            name='shared_with_permissions',
            field=models.JSONField(),
        ),
    ]
