# Generated by Django 5.0.6 on 2024-06-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0003_alter_productslistdatamodel_permissions_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslistdatamodel',
            name='permissions_owner',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='productslistdatamodel',
            name='shared_with_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
