# Generated by Django 5.0.6 on 2024-06-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0004_alter_productslistdatamodel_permissions_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslistdatamodel',
            name='shared_with_permissions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
