# Generated by Django 5.0.6 on 2024-06-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0005_alter_productslistdatamodel_shared_with_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productslistdatamodel',
            old_name='owner_id',
            new_name='id_owner',
        ),
        migrations.RenameField(
            model_name='productslistdatamodel',
            old_name='shared_with_id',
            new_name='id_shared_with',
        ),
    ]
