# Generated by Django 5.0.6 on 2024-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0006_rename_owner_id_productslistdatamodel_id_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productslistdatamodel',
            old_name='id_owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='productslistdatamodel',
            old_name='id_shared_with',
            new_name='shared_with_id',
        ),
        migrations.RemoveField(
            model_name='productslistdatamodel',
            name='permissions_owner',
        ),
        migrations.RemoveField(
            model_name='productslistdatamodel',
            name='shared_with_permissions',
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='owner_permissions_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='owner_permissions_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='owner_permissions_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='shared_with_permissions_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='shared_with_permissions_read',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='shared_with_permissions_write',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
