# Generated by Django 5.0.6 on 2024-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0007_rename_id_owner_productslistdatamodel_owner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductmodel',
            name='isPushed',
            field=models.BooleanField(default=False),
        ),
    ]
