# Generated by Django 5.0.6 on 2024-06-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0008_customproductmodel_ispushed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductmodel',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('piece', 'Piece'), ('g', 'G')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
