# Generated by Django 5.0.6 on 2024-07-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0009_customproductmodel_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslistdatamodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
