# Generated by Django 5.0.6 on 2024-07-04 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0010_alter_productslistdatamodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
