# Generated by Django 5.0.6 on 2024-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0013_customuser_ready_to_accept_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslistdatamodel',
            name='owner_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='shared_with_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
