# Generated by Django 5.0.6 on 2024-07-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0014_productslistdatamodel_owner_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productslistdatamodel',
            name='owner_permissions_admin',
        ),
        migrations.RemoveField(
            model_name='productslistdatamodel',
            name='owner_permissions_read',
        ),
        migrations.RemoveField(
            model_name='productslistdatamodel',
            name='owner_permissions_write',
        ),
        migrations.RemoveField(
            model_name='productslistdatamodel',
            name='shared_with_permissions_admin',
        ),
        migrations.RemoveField(
            model_name='productslistdatamodel',
            name='shared_with_permissions_read',
        ),
        migrations.RemoveField(
            model_name='productslistdatamodel',
            name='shared_with_permissions_write',
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productslistdatamodel',
            name='shared_type',
            field=models.CharField(choices=[('write', 'Write'), ('read', 'Read')], max_length=10, null=True),
        ),
    ]
