# Generated by Django 5.0.6 on 2024-07-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingListAPI', '0015_remove_productslistdatamodel_owner_permissions_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productslistdatamodel',
            old_name='owner_username',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='productslistdatamodel',
            old_name='shared_with_id',
            new_name='shared_id',
        ),
        migrations.RenameField(
            model_name='productslistdatamodel',
            old_name='shared_with_username',
            new_name='shared_name',
        ),
    ]
